# Generated by Django 6.0.2 on 2026-04-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='dept_head_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_lead_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
