# Generated by Django 6.0.2 on 2026-04-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='dept_head_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='jira_board_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_lead_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='dependency_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='skills',
            field=models.ManyToManyField(blank=True, to='team_registry.skill'),
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('upstream', 'Upstream'), ('downstream', 'Downstream')], default='upstream', max_length=20)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_source', to='team_registry.team')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_target', to='team_registry.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='depends_on',
            field=models.ManyToManyField(related_name='required_by', through='team_registry.TeamDependency', to='team_registry.team'),
        ),
    ]
