# Generated by Django 6.0.2 on 2026-04-25 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_registry', '0002_team_dept_head_name_team_team_lead_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('upstream', 'Upstream'), ('downstream', 'Downstream')], default='upstream', max_length=20)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_source', to='team_registry.team')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_target', to='team_registry.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='depends_on',
            field=models.ManyToManyField(related_name='required_by', through='team_registry.TeamDependency', to='team_registry.team'),
        ),
    ]
