# Generated by Django 6.0.2 on 2026-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_registry', '0003_teamdependency_team_depends_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='dependency_type',
        ),
        migrations.AlterField(
            model_name='team',
            name='skills',
            field=models.ManyToManyField(blank=True, to='team_registry.skill'),
        ),
    ]
