# Generated by Django 5.2.4 on 2026-04-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0001_initial'),
        ('teamapp', '0004_team_dependency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
