# Generated by Django 6.0.2 on 2026-04-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
