# Generated by Django 6.0.2 on 2026-04-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_team_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdependency',
            name='from_team',
        ),
        migrations.RemoveField(
            model_name='teamdependency',
            name='to_team',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='dependencies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='skills',
            field=models.ManyToManyField(related_name='teams', to='teamapp.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='TeamDependency',
        ),
    ]
