# Generated by Django 6.0.2 on 2026-04-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0003_remove_teamdependency_from_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='dependency_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
